#!/bin/bash

set -e
Version="V1.2"

function print_author() {

    echo "************************************************************************************"
    echo "*                                                                                  *"
    echo "*  About:                                                                          *"
    echo "*  I'm a engineer of Elecrow, if you have any question. email:keen@elecrow.com     *"
    echo "*  We truly hope you enjoy the product,for more great products please visit        *"
    echo "*  our company website: https://www.elecrow.com                                    *"
    echo "*  or Amazon store: www.amazon.com/shops/elecrow                                   *"
    echo "*                                                                                  *"
    echo "*                                                           Created  7 Apr. 2017   *"
    echo "*                                                          Modified 21 Apr. 2017   *"
    echo "*                                                                         by Keen  *"
    echo "*                                                                                  *"
    echo "************************************************************************************"

}

function print_help() {
    echo "***************************************************************************************"
    echo "*                                                                                     *"
    echo "**********************Wellcome to use Elecrow pitft Setup******************************"
    echo "*                                                                                     *"
    echo "*              Switch to 5 inch LCD.  Example: sudo ./Elecrow-LCD5                    *"
    echo "*    [Angle]   Support rotation: 0/90/180/270. Example: sudo ./Elecrow-LCD5 270       *"
    echo "*    hdmi      Switch to HDMI.          Example: sudo ./Elecrow-LCD5 hdmi             *"
    echo "*    A         Print about the author.  Example: sudo ./Elecrow-LCD5 A                *"
    echo "*    H         Print this help.         Example: sudo ./Elecrow-LCD5 H                *"
    echo "*                                                                                     *"
    echo "*    NOTE:     Only support Elecrow 5 Inch LCD.                                       *"
    echo "*                                                                                     *"
    echo "*                                                                            V1.2     *"
    echo "***************************************************************************************"
}

group=Elecrow
function info() {
    system="$1"
    group="${system}"
    shift
    FG="1;32m"
    BG="40m"
    echo -e "[\033[${FG}\033[${BG}${system}\033[0m] $*"
}

function bail() {
    FG="1;31m"
    BG="40m"
    echo -en "[\033[${FG}\033[${BG}${group}\033[0m] "
    if [ -z "$1" ]; then
        echo "Exiting due to error"
    else
        echo "Exiting due to error: $*"
    fi
    exit 1
}

function ask() {
    # http://djm.me/ask
    while true; do

        if [ "${2:-}" = "Y" ]; then
            prompt="Y/n"
            default=Y
        elif [ "${2:-}" = "N" ]; then
            prompt="y/N"
            default=N
        else
            prompt="y/n"
            default=
        fi

        # Ask the question
        read -p "$1 [$prompt] " REPLY

        # Default?
        if [ -z "$REPLY" ]; then
            REPLY=$default
        fi

        # Check if the reply is valid
        case "$REPLY" in
            Y*|y*) return 0 ;;
            N*|n*) return 1 ;;
        esac
    done
}

function update_configtxt() {

if grep -q "elecrow-pitft-setup" "/boot/config.txt"; then
        echo "Config is already update..."
else
date=`date`
cat >> /boot/config.txt <<EOF
# --- added by elecrow-pitft-setup $date ---
hdmi_force_hotplug=1
max_usb_current=1
hdmi_drive=1
hdmi_group=2
hdmi_mode=1
hdmi_mode=87
hdmi_cvt 800 480 60 6 0 0 0
dtoverlay=ads7846,cs=1,penirq=25,penirq_pull=2,speed=50000,keep_vref_on=0,swapxy=0,pmax=255,xohms=150,xmin=200,xmax=3900,ymin=200,ymax=3900
display_rotate=0
# --- end elecrow-pitft-setup $date ---
EOF
fi
}

function pi_rotation(){

if [ "${rotation}" !=  "0" ] && [ "${rotation}" !=  "90" ] && [ "${rotation}" !=  "180" ] && [ "${rotation}" !=  "270" ]; then
	bail "Support only rotation: 0/90/180/270"
exit 1
fi
sed -i '/display_rotate/'d /boot/config.txt
sed -i '/end elecrow-pitft-setup/'d /boot/config.txt
date=`date`
cat >> /boot/config.txt <<EOF
display_rotate=$[$rotation/90]
# --- end elecrow-pitft-setup $date ---
EOF
info PITFT "Calibration screen..."
calibration
}

function calibration() {
rm -f /etc/X11/xorg.conf.d/99-calibration.conf
if [ "${rotation}" == "0" ]; then
        calib="208 3905 288 3910"
	dn=0
fi
if [ "${rotation}" == "90" ]; then
        calib="208 3905 3910 288"
	dn=1
fi
if [ "${rotation}" == "180" ]; then
        calib="3905 208 3910 288"
	dn=0
fi
if [ "${rotation}" == "270" ]; then
        calib="3905 208 288 3910"
	dn=1
fi
info PITFT "Calibration success!"

date=`date`
cat > /etc/X11/xorg.conf.d/99-calibration.conf <<EOF
# --- added by elecrow-pitft-setup $date ---
Section "InputClass"
	Identifier	"calibration"
	MatchProduct	"ADS7846 Touchscreen"
	Option	"Calibration"	"$calib"
	Option	"SwapAxes"	"$dn"
EndSection
# --- end elecrow-pitft-setup $date ---
EOF
}



function update_xorg() {

mkdir -p /etc/X11/xorg.conf.d
touch /etc/X11/xorg.conf.d/99-calibration.conf

if grep -q "elecrow-pitft-setup" "/etc/X11/xorg.conf.d/99-calibration.conf"; then
        echo "Xorg is already update."
else

date=`date`
cat > /etc/X11/xorg.conf.d/99-calibration.conf <<EOF
# --- added by elecrow-pitft-setup $date ---
Section "InputClass"
	Identifier	"calibration"
	MatchProduct	"ADS7846 Touchscreen"
	Option	"Calibration"	"208 3905 288 3910"
	Option	"SwapAxes"	"0"
EndSection
# --- end elecrow-pitft-setup $date ---
EOF
fi
}

function install_console() {

if ! grep -q 'fbcon=map:10 fbcon=font:ProFont6x11' /boot/cmdline.txt; then
     sed -i 's/rootwait/rootwait fbcon=map:10 fbcon=font:ProFont6x11/g' "/boot/cmdline.txt"
else
     echo "cmdline is already update..."
fi

}

function switch_hdmi(){

info HDMI "Switch to HDMI..."
rm -f /etc/X11/xorg.conf.d/99-calibration.conf
rm -f /usr/share/X11/xorg.conf.d/45-evdev.conf
sed -i 's/rootwait fbcon=map:10 fbcon=font:ProFont6x11/rootwait/g' "/boot/cmdline.txt"
sed -i '/added by elecrow-pitft-setup/,/end elecrow-pitft-setup/d' "/boot/config.txt"
info HDMI "Switch success!"

}

function update_evdev(){

apt-get install xserver-xorg-input-evdev

}

function config_evdev(){

cat > /usr/share/X11/xorg.conf.d/45-evdev.conf <<EOF
# --- added by elecrow-pitft-setup $date ---
Section "InputClass"
        Identifier "evdev pointer catchall"
        MatchIsPointer "on"
        MatchDevicePath "/dev/input/event*"
        Driver "evdev"
EndSection

Section "InputClass"
        Identifier "evdev keyboard catchall"
        MatchIsKeyboard "on"
        MatchDevicePath "/dev/input/event*"
        Driver "evdev"
EndSection

Section "InputClass"
        Identifier "evdev touchpad catchall"
        MatchIsTouchpad "on"
        MatchDevicePath "/dev/input/event*"
        Driver "evdev"
EndSection

Section "InputClass"
        Identifier "evdev tablet catchall"
        MatchIsTablet "on"
        MatchDevicePath "/dev/input/event*"
        Driver "evdev"
EndSection

Section "InputClass"
        Identifier "evdev touchscreen catchall"
        MatchIsTouchscreen "on"
        MatchDevicePath "/dev/input/event*"
        Driver "evdev"
EndSection
# --- end elecrow-pitft-setup $date ---
EOF

}

function check_kernel(){

rm -f /etc/kernelinfo.txt
cat >> /etc/kernelinfo.txt <<EOF
# --- added by elecrow-pitft-setup $date ---
$(uname -a)
# --- end elecrow-pitft-setup $date ---
EOF

}

function install_driver(){

print_help

info PITFT "Checking kernel infomation..."
check_kernel || bail "Check fail..."

if grep -q "4.4.5" "/etc/kernelinfo.txt"; then
  info PITFT "Updating evdev..."
  update_evdev || bail "Unable to update evdev..."

  info PITFT "Config evdev..."
  config_evdev || bail "Unable to config evdev..."
fi

info PITFT "Updating config.txt..."
update_configtxt || bail "Unable to update config..."

info PITFT "Updating X11 default calibration..."
update_xorg || bail "Unable to update 99-calibration.conf..."

info PITFT "Updating console to PiTFT..."
install_console || bail "Unable to configure console..."


info PITFT "Install success!"
info PITFT "Notes:"

echo "************************************************************************************"
echo "*                                                                                  *"
echo "* Please don't run rpi-update.                                                     *"
echo "* If you have any technical questions                                              *"
echo "* Please feel free to contact our support staff via email at keen@elecrow.com      *"
echo "* We truly hope you enjoy the product,for more great products please visit         *"
echo "* our company website: https://www.elecrow.com                                     *"
echo "* or Amazon store: www.amazon.com/shops/elecrow                                    *"
echo "*                                                                                  *"
echo "************************************************************************************"

}

function verify_install_driver(){

info PITFT "If you want to install the driver, it must be connect to the network..."
info PITFT "Note: Only support elecrow 3.5 inch LCD..."
info PITFT "Check system version..."
wget -O /boot/LCD35.txt https://github.com/SmrazaKeen/verification/raw/master/LCD35.txt
info PITFT "View the latest driver version"
var1=$(grep -i "^Version" /boot/LCD35.txt | cut -d: -f 3 2>/dev/null)
info PITFT "Current version_$Version"
info PITFT "Latest $var1"
info PITFT "If you want to update the version, you need to remove the old version and download the latest version"
if grep -q "Raspbian-Kali-Ubuntu_Mate-Retropie-Octopi" "/boot/LCD35.txt"; then
	rm -f /boot/LCD35.txt
	info PITFT "Install the driver..."
	install_driver || bail "Install failed.."
else
	echo "If there is no networking will prompt this error..."
	bail "Please use Elecrow legitimate driver to install..."
fi

}

function reboot_sys(){

read -p "Reboot to apply changes? (y/n): " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
       reboot
fi
exit 1

}

info PITFT "Check system..."
if [[ $EUID -ne 0 ]]; then
    print_help
    bail "elecrow-pitft-setup must be run as root. try:"
fi

if [ $# -eq 0 ]; then
info PITFT "Install the driver..."
install_driver || bail "Install failed.."
#verify_install_driver
#check_kernel
print_author
reboot_sys
elif [ $1 == "0" ] || [ $1 == "90" ] || [ $1 == "180" ] || [ $1 == "270" ]; then
rotation=$1
pi_rotation
reboot_sys
elif [[ $1 == "hdmi" ]];then
switch_hdmi
reboot_sys
elif [[ $1 == "A" ]];then
print_author
exit 1
elif [[ $1 == "H" ]];then
print_help
exit 1
else
print_help
exit 1
fi

